export type IamAction =
	| "SES:SendEmail"
	| "SES:SendRawEmail"
	| "ec2:AssociateAddress"
	| "ec2:DescribeAddresses"
	| "ec2:DisassociateAddress"
	| "iam:PassRole"
	| "lambda:CreateFunction"
	| "lambda:UpdateFunctionCode"
	| "lambda:UpdateFunctionConfiguration"
	| "logs:CreateLogGroup"
	| "logs:PutRetentionPolicy"
	| "s3:DeleteObject"
	| "s3:GetObject"
	| "s3:ListBucket"
	| "s3:PutObject"
