module.exports = {
  env: { browser: true, es2020: true, node: true },
  extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"],
  parser: "@typescript-eslint/parser",
  plugins: [
    "@typescript-eslint",
    "eslint-plugin-tsdoc",
    "import",
    "prettier",
    "simple-import-sort",
  ],
  root: true,
  rules: {
    "@typescript-eslint/ban-ts-comment": "warn",
    "@typescript-eslint/no-array-constructor": "off",
    "@typescript-eslint/no-duplicate-imports": "error",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-extra-semi": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        // Follow the TypeScript convention to prepend an underscore to
        // ignore when a variable is not used.
        // This works also with TypeScript compiler options
        // ```json
        // "noUnusedLocals": true,
        // "noUnusedParameters": true,
        // ```
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "arrow-body-style": ["error", "as-needed"],
    "block-scoped-var": "error",
    "default-param-last": "error",
    "dot-notation": "error",
    eqeqeq: "error",
    "func-style": ["warn", "expression"],
    "import/extensions": ["error", "ignorePackages"],
    "import/first": "error",
    "import/newline-after-import": "error",
    "import/no-cycle": "error",
    "import/no-extraneous-dependencies": ["error"],
    "import/no-internal-modules": ["error"],
    "max-depth": ["error", 5],
    "no-case-declarations": "error",
    "no-console": ["error", { allow: ["error", "info", "warn"] }],
    "no-extra-label": "warn",
    "no-floating-decimal": "error",
    "no-global-assign": "error",
    "no-implicit-coercion": "warn",
    "no-implicit-globals": "error",
    "no-lonely-if": "error",
    "no-multi-assign": "error",
    "no-warning-comments": "warn",
    "prettier/prettier": "error",
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": "error",
    "sort-keys": [
      "error",
      "asc",
      {
        allowLineSeparatedGroups: true,
        caseSensitive: true,
        minKeys: 7,
        natural: true,
      },
    ],
    "tsdoc/syntax": "error",
  },
};
